name: Build and Deploy

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    name: Build Android APK
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install --legacy-peer-deps
    
    - name: Debug token
      run: |
        if [ -n "${{ secrets.EXPO_TOKEN }}" ]; then
          echo "EXPO_TOKEN is set (length: ${#EXPO_TOKEN})"
        else
          echo "EXPO_TOKEN is NOT set"
        fi
    
    - name: Setup EAS
      uses: expo/expo-github-action@v8
      with:
        eas-version: latest
        token: ${{ secrets.EXPO_TOKEN }}
    
    - name: Build Android APK
      run: |
        if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
          echo "Error: EXPO_TOKEN is not set"
          exit 1
        fi
        eas build --platform android --profile production --non-interactive
    
    - name: Upload Android APK
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: |
          *.apk
          *.aab
        retention-days: 30

  build-ios:
    runs-on: macos-latest
    name: Build iOS IPA
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install --legacy-peer-deps
    
    - name: Setup EAS
      uses: expo/expo-github-action@v8
      with:
        eas-version: latest
        token: ${{ secrets.EXPO_TOKEN }}
    
    - name: Build iOS IPA
      run: |
        if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
          echo "Error: EXPO_TOKEN is not set"
          exit 1
        fi
        eas build --platform ios --profile production --non-interactive
    
    - name: Upload iOS IPA
      uses: actions/upload-artifact@v4
      with:
        name: ios-ipa
        path: |
          *.ipa
        retention-days: 30

  build-web:
    runs-on: ubuntu-latest
    name: Build Web App
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install --legacy-peer-deps
    
    - name: Build Web App
      run: npx expo export --platform web
    
    - name: Upload Web Build
      uses: actions/upload-artifact@v4
      with:
        name: web-build
        path: dist/
        retention-days: 30 